// GENERATED by tools/generate_from_schema.py from schema/. Do not edit:
// change the schema (or the generator) and run the tool.

/** IAES enumerations. Generated from schema/; see the header. */

/**
 * Condition of the asset. This is NOT a priority: it does not say how
 * urgently anyone should respond. Which urgency a condition deserves is the
 * consumer's judgment, because the consumer knows what else is running.
 *
 * Schema: asset.health, data.severity.
 */
export const Severity = {
  INFO: "info",
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  CRITICAL: "critical",
} as const;
export type Severity = (typeof Severity)[keyof typeof Severity];

/**
 * Type of measurement. Open: the examples below are ADVISORY and constrain
 * nothing. A consumer MUST NOT reject an event because its measurement_type
 * is not among them. Advisory: the schema leaves this field open, so these
 * are conveniences, never a constraint. The last 6 were published by the
 * SDKs before the schema listed its examples.
 *
 * Schema: asset.measurement, data.measurement_type.
 */
export const MeasurementType = {
  VIBRATION_VELOCITY: "vibration_velocity",
  VIBRATION_ACCELERATION: "vibration_acceleration",
  VIBRATION_DISPLACEMENT: "vibration_displacement",
  TEMPERATURE: "temperature",
  CURRENT: "current",
  VOLTAGE: "voltage",
  POWER: "power",
  ENERGY: "energy",
  PRESSURE: "pressure",
  FLOW: "flow",
  SPEED: "speed",
  POWER_FACTOR: "power_factor",
  THD_VOLTAGE: "thd_voltage",
  THD_CURRENT: "thd_current",
  FREQUENCY: "frequency",
  REACTIVE_POWER: "reactive_power",
  CUSTOM: "custom",
} as const;
export type MeasurementType = (typeof MeasurementType)[keyof typeof MeasurementType];

/**
 * Signal processing method applied to the value (ISO 17359 §6.3). Required
 * for vibration measurements to disambiguate.
 *
 * Schema: asset.measurement, data.units_qualifier.
 */
export const UnitsQualifier = {
  RMS: "rms",
  PEAK: "peak",
  PEAK_TO_PEAK: "peak_to_peak",
  AVERAGE: "average",
  TRUE_RMS: "true_rms",
} as const;
export type UnitsQualifier = (typeof UnitsQualifier)[keyof typeof UnitsQualifier];

/**
 * Health status. IAES's own vocabulary: any correspondence to an external
 * standard is unverified and is not asserted here. The field name is
 * retained for compatibility with 1.x.
 *
 * Schema: asset.health, data.iso_13374_status.
 */
export const ISO13374Status = {
  UNKNOWN: "unknown",
  NORMAL: "normal",
  SATISFACTORY: "satisfactory",
  UNSATISFACTORY: "unsatisfactory",
  UNACCEPTABLE: "unacceptable",
  IMMINENT_FAILURE: "imminent_failure",
  FAILED: "failed",
} as const;
export type ISO13374Status = (typeof ISO13374Status)[keyof typeof ISO13374Status];

/**
 * Temporal trend of the assessed condition relative to the previous
 * assessment. IAES's own vocabulary: any correspondence to an external
 * standard is unverified and is not asserted here.
 *
 * Schema: asset.health, data.condition_trend.
 */
export const ConditionTrend = {
  WORSENING: "worsening",
  STABLE: "stable",
  IMPROVING: "improving",
} as const;
export type ConditionTrend = (typeof ConditionTrend)[keyof typeof ConditionTrend];

/**
 * Urgency of the proposed response. This is NOT a severity: it does not
 * describe the condition of the asset. The two catalogs share the values
 * low, medium and high, and mean different things by them.
 *
 * Schema: maintenance.work_order_intent, data.priority.
 */
export const WorkOrderPriority = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  EMERGENCY: "emergency",
} as const;
export type WorkOrderPriority = (typeof WorkOrderPriority)[keyof typeof WorkOrderPriority];

/**
 * Completion status of the work order
 *
 * Schema: maintenance.completion, data.status.
 */
export const CompletionStatus = {
  COMPLETED: "completed",
  PARTIALLY_COMPLETED: "partially_completed",
  CANCELLED: "cancelled",
  DEFERRED: "deferred",
} as const;
export type CompletionStatus = (typeof CompletionStatus)[keyof typeof CompletionStatus];

/**
 * Level in the asset hierarchy
 *
 * Schema: asset.hierarchy, data.hierarchy_level.
 */
export const HierarchyLevel = {
  ORGANIZATION: "organization",
  PLANT: "plant",
  AREA: "area",
  EQUIPMENT: "equipment",
} as const;
export type HierarchyLevel = (typeof HierarchyLevel)[keyof typeof HierarchyLevel];

/**
 * Relationship to the referenced asset
 *
 * Schema: asset.hierarchy, data.relationship_type.
 */
export const RelationshipType = {
  PARENT_OF: "parent_of",
  CHILD_OF: "child_of",
  SIBLING_OF: "sibling_of",
  DEPENDS_ON: "depends_on",
} as const;
export type RelationshipType = (typeof RelationshipType)[keyof typeof RelationshipType];

/**
 * Current registration state of the sensor
 *
 * Schema: sensor.registration, data.registration_status.
 */
export const RegistrationStatus = {
  DISCOVERED: "discovered",
  REGISTERED: "registered",
  CALIBRATED: "calibrated",
  DECOMMISSIONED: "decommissioned",
} as const;
export type RegistrationStatus = (typeof RegistrationStatus)[keyof typeof RegistrationStatus];
