// GENERATED by tools/generate_from_schema.py from schema/. Do not edit:
// change the schema (or the generator) and run the tool.

/** What the schemas say about shape, as data. Generated; see the header. */

/** Event types whose schema is published. */
export const PUBLISHED_EVENT_TYPES: ReadonlySet<string> = new Set([
  "asset.health",
  "asset.hierarchy",
  "asset.measurement",
  "maintenance.completion",
  "maintenance.spare_part_usage",
  "maintenance.work_order_intent",
  "sensor.registration",
]);

/** The schema file of each published type. */
export const SCHEMA_FILES: Readonly<Record<string, string>> = {
  "asset.health": "asset-health.schema.json",
  "asset.hierarchy": "asset-hierarchy.schema.json",
  "asset.measurement": "asset-measurement.schema.json",
  "maintenance.completion": "maintenance-completion.schema.json",
  "maintenance.spare_part_usage": "maintenance-spare-part-usage.schema.json",
  "maintenance.work_order_intent": "maintenance-work-order-intent.schema.json",
  "sensor.registration": "sensor-registration.schema.json",
};

/** Required fields of `data`, per type. */
export const REQUIRED_DATA_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "asset.health": ["health_index", "severity"],
  "asset.hierarchy": ["hierarchy_level", "relationship_type"],
  "asset.measurement": ["measurement_type", "value", "unit"],
  "maintenance.completion": ["status", "work_order_id"],
  "maintenance.spare_part_usage": ["work_order_id", "spare_part_id", "quantity_used"],
  "maintenance.work_order_intent": ["title", "priority"],
  "sensor.registration": ["sensor_id", "registration_status"],
};

/** Closed catalogues: the values the schema allows, per type and field. */
export const CATALOGS: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = {
  "asset.health": {
    severity: ["info", "low", "medium", "high", "critical"],
    condition_trend: ["worsening", "stable", "improving"],
    iso_13374_status: ["unknown", "normal", "satisfactory", "unsatisfactory", "unacceptable", "imminent_failure", "failed"],
  },
  "asset.hierarchy": {
    hierarchy_level: ["organization", "plant", "area", "equipment"],
    relationship_type: ["parent_of", "child_of", "sibling_of", "depends_on"],
  },
  "asset.measurement": {
    units_qualifier: ["rms", "peak", "peak_to_peak", "average", "true_rms"],
  },
  "maintenance.completion": {
    status: ["completed", "partially_completed", "cancelled", "deferred"],
  },
  "maintenance.work_order_intent": {
    priority: ["low", "medium", "high", "emergency"],
    triggered_by: ["alert", "schedule", "manual", "threshold", "ai_diagnosis"],
  },
  "sensor.registration": {
    registration_status: ["discovered", "registered", "calibrated", "decommissioned"],
  },
};
