# GENERATED by tools/generate_from_schema.py from schema/. Do not edit:
# change the schema (or the generator) and run the tool.

"""IAES enumerations. Generated from schema/; see the header."""

from enum import Enum


class Severity(str, Enum):
    """Condition of the asset. This is NOT a priority: it does not say how
    urgently anyone should respond. Which urgency a condition deserves is
    the consumer's judgment, because the consumer knows what else is
    running.

    Schema: asset.health, data.severity.
    """

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MeasurementType(str, Enum):
    """Type of measurement. Open: the examples below are ADVISORY and constrain
    nothing. A consumer MUST NOT reject an event because its
    measurement_type is not among them. Advisory: the schema leaves this
    field open, so these are conveniences, never a constraint. The last 6
    were published by the SDKs before the schema listed its examples.

    Schema: asset.measurement, data.measurement_type.
    """

    VIBRATION_VELOCITY = "vibration_velocity"
    VIBRATION_ACCELERATION = "vibration_acceleration"
    VIBRATION_DISPLACEMENT = "vibration_displacement"
    TEMPERATURE = "temperature"
    CURRENT = "current"
    VOLTAGE = "voltage"
    POWER = "power"
    ENERGY = "energy"
    PRESSURE = "pressure"
    FLOW = "flow"
    SPEED = "speed"
    POWER_FACTOR = "power_factor"
    THD_VOLTAGE = "thd_voltage"
    THD_CURRENT = "thd_current"
    FREQUENCY = "frequency"
    REACTIVE_POWER = "reactive_power"
    CUSTOM = "custom"


class UnitsQualifier(str, Enum):
    """Signal processing method applied to the value (ISO 17359 §6.3). Required
    for vibration measurements to disambiguate.

    Schema: asset.measurement, data.units_qualifier.
    """

    RMS = "rms"
    PEAK = "peak"
    PEAK_TO_PEAK = "peak_to_peak"
    AVERAGE = "average"
    TRUE_RMS = "true_rms"


class ISO13374Status(str, Enum):
    """Health status. IAES's own vocabulary: any correspondence to an external
    standard is unverified and is not asserted here. The field name is
    retained for compatibility with 1.x.

    Schema: asset.health, data.iso_13374_status.
    """

    UNKNOWN = "unknown"
    NORMAL = "normal"
    SATISFACTORY = "satisfactory"
    UNSATISFACTORY = "unsatisfactory"
    UNACCEPTABLE = "unacceptable"
    IMMINENT_FAILURE = "imminent_failure"
    FAILED = "failed"


class ConditionTrend(str, Enum):
    """Temporal trend of the assessed condition relative to the previous
    assessment. IAES's own vocabulary: any correspondence to an external
    standard is unverified and is not asserted here.

    Schema: asset.health, data.condition_trend.
    """

    WORSENING = "worsening"
    STABLE = "stable"
    IMPROVING = "improving"


class WorkOrderPriority(str, Enum):
    """Urgency of the proposed response. This is NOT a severity: it does not
    describe the condition of the asset. The two catalogs share the values
    low, medium and high, and mean different things by them.

    Schema: maintenance.work_order_intent, data.priority.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    EMERGENCY = "emergency"


class CompletionStatus(str, Enum):
    """Completion status of the work order

    Schema: maintenance.completion, data.status.
    """

    COMPLETED = "completed"
    PARTIALLY_COMPLETED = "partially_completed"
    CANCELLED = "cancelled"
    DEFERRED = "deferred"


class HierarchyLevel(str, Enum):
    """Level in the asset hierarchy

    Schema: asset.hierarchy, data.hierarchy_level.
    """

    ORGANIZATION = "organization"
    PLANT = "plant"
    AREA = "area"
    EQUIPMENT = "equipment"


class RelationshipType(str, Enum):
    """Relationship to the referenced asset

    Schema: asset.hierarchy, data.relationship_type.
    """

    PARENT_OF = "parent_of"
    CHILD_OF = "child_of"
    SIBLING_OF = "sibling_of"
    DEPENDS_ON = "depends_on"


class RegistrationStatus(str, Enum):
    """Current registration state of the sensor

    Schema: sensor.registration, data.registration_status.
    """

    DISCOVERED = "discovered"
    REGISTERED = "registered"
    CALIBRATED = "calibrated"
    DECOMMISSIONED = "decommissioned"


class UpDownState(str, Enum):
    """The state from this event's timestamp on: able (up) or unable (down) to
    perform as required (ISO 14224:2016, 3.96 and 3.15).

    Schema: asset.state, data.state.
    """

    UP = "up"
    DOWN = "down"


class DownKind(str, Enum):
    """The two branches of down time (ISO 14224:2016, Table 4). Required when
    state is down.

    Schema: asset.state, data.down_kind.
    """

    PLANNED = "planned"
    UNPLANNED = "unplanned"


class DownCause(str, Enum):
    """The four branches of down time (ISO 14224:2016, Table 4). Open: the
    examples are the published values, and a consumer MUST treat any other
    as not classified, never as an error. A published value must agree with
    down_kind: the first two are planned, the last two unplanned. A trip is
    an other unplanned outage, not corrective maintenance. Advisory: the
    schema leaves this field open, so these are conveniences, never a
    constraint.

    Schema: asset.state, data.down_cause.
    """

    PREVENTIVE_MAINTENANCE = "preventive_maintenance"
    OTHER_PLANNED = "other_planned"
    CORRECTIVE_MAINTENANCE = "corrective_maintenance"
    OTHER_UNPLANNED = "other_unplanned"


class UpMode(str, Enum):
    """What the asset was doing while up, when the producer knows it: the up-
    time leaves of ISO 14224:2016 Table 4, plus externally disabled time
    (3.38, Note 3). Open: the examples are the published values, and a
    consumer MUST treat any other as not classified, never as an error.
    Whether a mode counts as operating time is the consumer's
    classification. Advisory: the schema leaves this field open, so these
    are conveniences, never a constraint.

    Schema: asset.state, data.up_mode.
    """

    START_UP = "start_up"
    RUNNING = "running"
    RUN_DOWN = "run_down"
    HOT_STANDBY = "hot_standby"
    IDLE = "idle"
    COLD_STANDBY = "cold_standby"
    EXTERNALLY_DISABLED = "externally_disabled"


class PreviousState(str, Enum):
    """What the producer believed the state was just before this event. unknown
    when it starts, or regains sight of the asset, without knowing it.

    Schema: asset.state, data.previous_state.
    """

    UP = "up"
    DOWN = "down"
    UNKNOWN = "unknown"
