# GENERATED by tools/generate_from_schema.py from schema/. Do not edit:
# change the schema (or the generator) and run the tool.

"""IAES enumerations. Generated from schema/; see the header."""

from enum import Enum


class Severity(str, Enum):
    """Condition of the asset. This is NOT a priority: it does not say how
    urgently anyone should respond. Which urgency a condition deserves is
    the consumer's judgment, because the consumer knows what else is
    running.

    Schema: asset.health, data.severity.
    """

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MeasurementType(str, Enum):
    """Type of measurement. Open: the examples below are ADVISORY and constrain
    nothing. A consumer MUST NOT reject an event because its
    measurement_type is not among them. Advisory: the schema leaves this
    field open, so these are conveniences, never a constraint. The last 6
    were published by the SDKs before the schema listed its examples.

    Schema: asset.measurement, data.measurement_type.
    """

    VIBRATION_VELOCITY = "vibration_velocity"
    VIBRATION_ACCELERATION = "vibration_acceleration"
    VIBRATION_DISPLACEMENT = "vibration_displacement"
    TEMPERATURE = "temperature"
    CURRENT = "current"
    VOLTAGE = "voltage"
    POWER = "power"
    ENERGY = "energy"
    PRESSURE = "pressure"
    FLOW = "flow"
    SPEED = "speed"
    POWER_FACTOR = "power_factor"
    THD_VOLTAGE = "thd_voltage"
    THD_CURRENT = "thd_current"
    FREQUENCY = "frequency"
    REACTIVE_POWER = "reactive_power"
    CUSTOM = "custom"


class UnitsQualifier(str, Enum):
    """Signal processing method applied to the value (ISO 17359 §6.3). Required
    for vibration measurements to disambiguate.

    Schema: asset.measurement, data.units_qualifier.
    """

    RMS = "rms"
    PEAK = "peak"
    PEAK_TO_PEAK = "peak_to_peak"
    AVERAGE = "average"
    TRUE_RMS = "true_rms"


class ISO13374Status(str, Enum):
    """Health status. IAES's own vocabulary: any correspondence to an external
    standard is unverified and is not asserted here. The field name is
    retained for compatibility with 1.x.

    Schema: asset.health, data.iso_13374_status.
    """

    UNKNOWN = "unknown"
    NORMAL = "normal"
    SATISFACTORY = "satisfactory"
    UNSATISFACTORY = "unsatisfactory"
    UNACCEPTABLE = "unacceptable"
    IMMINENT_FAILURE = "imminent_failure"
    FAILED = "failed"


class ConditionTrend(str, Enum):
    """Temporal trend of the assessed condition relative to the previous
    assessment. IAES's own vocabulary: any correspondence to an external
    standard is unverified and is not asserted here.

    Schema: asset.health, data.condition_trend.
    """

    WORSENING = "worsening"
    STABLE = "stable"
    IMPROVING = "improving"


class WorkOrderPriority(str, Enum):
    """Urgency of the proposed response. This is NOT a severity: it does not
    describe the condition of the asset. The two catalogs share the values
    low, medium and high, and mean different things by them.

    Schema: maintenance.work_order_intent, data.priority.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    EMERGENCY = "emergency"


class CompletionStatus(str, Enum):
    """Completion status of the work order

    Schema: maintenance.completion, data.status.
    """

    COMPLETED = "completed"
    PARTIALLY_COMPLETED = "partially_completed"
    CANCELLED = "cancelled"
    DEFERRED = "deferred"


class HierarchyLevel(str, Enum):
    """Level in the asset hierarchy

    Schema: asset.hierarchy, data.hierarchy_level.
    """

    ORGANIZATION = "organization"
    PLANT = "plant"
    AREA = "area"
    EQUIPMENT = "equipment"


class RelationshipType(str, Enum):
    """Relationship to the referenced asset

    Schema: asset.hierarchy, data.relationship_type.
    """

    PARENT_OF = "parent_of"
    CHILD_OF = "child_of"
    SIBLING_OF = "sibling_of"
    DEPENDS_ON = "depends_on"


class RegistrationStatus(str, Enum):
    """Current registration state of the sensor

    Schema: sensor.registration, data.registration_status.
    """

    DISCOVERED = "discovered"
    REGISTERED = "registered"
    CALIBRATED = "calibrated"
    DECOMMISSIONED = "decommissioned"
