#!/usr/bin/env python3
"""Generate, from schema/, every rule the implementations need as code.

A rule of IAES is written once. If it is about shape (which types are
published, which fields exist, which are required, which values a closed field
takes) it is written in schema/. The implementations either read the schemas at
run time (the validators do), or take the rule from the files this tool writes,
or are compared with the schemas by a test. They never copy it.

Until this tool, the closed catalogues were copied by hand into the Python SDK,
the TypeScript SDK and the n8n Emit form. The two SDKs were held to the schemas
by tests/test_catalogs.py; the n8n form was held by nothing, and on 2026-10-06
it was missing `unknown` (iso_13374_status) and `alert` (triggered_by), so an
n8n user could not emit two values the schemas allow.

Writes, in both languages:

  src/iaes/_from_schema.py  npm/src/fromSchema.ts   published types, their schema
                                                    files, closed catalogues and
                                                    required data fields
  src/iaes/enums.py         npm/src/enums.ts        the SDK's enumerations

The one list here that is not in the schemas is SDK_ADDITIONS: measurement
types the SDKs published before the schema listed its examples. Removing them
would break code that uses them, so they stay, declared.

Stdlib only, like the other tools.

  python tools/generate_from_schema.py           # write
  python tools/generate_from_schema.py --check   # fail if any output is stale
"""

import argparse
import json
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER_PY = (
    "# GENERATED by tools/generate_from_schema.py from schema/. Do not edit:\n"
    "# change the schema (or the generator) and run the tool.\n"
)
HEADER_TS = (
    "// GENERATED by tools/generate_from_schema.py from schema/. Do not edit:\n"
    "// change the schema (or the generator) and run the tool.\n"
)

#: Which closed catalogue each SDK enumeration publishes, in the order the
#: enumerations have always been declared. (event type, field) -> class name.
ENUMS = [
    ("Severity", "asset.health", "severity"),
    ("MeasurementType", "asset.measurement", "measurement_type"),
    ("UnitsQualifier", "asset.measurement", "units_qualifier"),
    ("ISO13374Status", "asset.health", "iso_13374_status"),
    ("ConditionTrend", "asset.health", "condition_trend"),
    ("WorkOrderPriority", "maintenance.work_order_intent", "priority"),
    ("CompletionStatus", "maintenance.completion", "status"),
    ("HierarchyLevel", "asset.hierarchy", "hierarchy_level"),
    ("RelationshipType", "asset.hierarchy", "relationship_type"),
    ("RegistrationStatus", "sensor.registration", "registration_status"),
    # asset.state (IAES 2.1, IAES-RFC-010). Not named AssetState: the model class takes that name.
    ("UpDownState", "asset.state", "state"),
    ("DownKind", "asset.state", "down_kind"),
    ("DownCause", "asset.state", "down_cause"),
    ("UpMode", "asset.state", "up_mode"),
    ("PreviousState", "asset.state", "previous_state"),
]

#: measurement_type is OPEN in the schema: it carries advisory `examples`, not an
#: enum. The SDKs published these six before the schema listed its examples, and
#: removing a constant breaks the code that uses it. Declared, not hidden.
SDK_ADDITIONS = {
    "measurement_type": ["power_factor", "thd_voltage", "thd_current", "frequency",
                         "reactive_power", "custom"],
}


def schemas():
    """event type -> (file name, parsed schema), for every published event schema."""
    out = {}
    for path in sorted((ROOT / "schema").glob("*.schema.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        event_type = doc["$id"].rsplit("/", 1)[-1]
        if event_type != "envelope":
            out[event_type] = (path.name, doc)
    return out


def data_properties(doc):
    return doc.get("properties", {}).get("data", {}).get("properties", {})


def index():
    """Everything the generated files carry, read from the schemas."""
    found = schemas()
    published = sorted(found)
    files = {t: found[t][0] for t in published}
    required = {t: list(found[t][1]["properties"]["data"].get("required", [])) for t in published}
    catalogs = {}
    for t in published:
        for field, spec in data_properties(found[t][1]).items():
            if "enum" in spec:
                catalogs.setdefault(t, {})[field] = [v for v in spec["enum"] if v is not None]
    return found, published, files, required, catalogs


def enum_values(found, event_type, field):
    spec = data_properties(found[event_type][1])[field]
    if "enum" in spec:
        return [v for v in spec["enum"] if v is not None], spec.get("description", "")
    values = list(spec.get("examples", [])) + [v for v in SDK_ADDITIONS.get(field, [])
                                                 if v not in spec.get("examples", [])]
    note = " Advisory: the schema leaves this field open, so these are conveniences, never a constraint."
    if SDK_ADDITIONS.get(field):
        note += (" The last %d were published by the SDKs before the schema listed its examples."
                 % len(SDK_ADDITIONS[field]))
    return values, spec.get("description", "") + note


def wrap(text, width, prefix):
    return "\n".join(textwrap.wrap(" ".join(text.split()), width=width, initial_indent=prefix,
                                   subsequent_indent=prefix))


def python_from_schema(published, files, required, catalogs):
    lines = [HEADER_PY, '"""What the schemas say about shape, as data. Generated; see the header."""', "",
             "#: Event types whose schema is published.",
             "PUBLISHED_EVENT_TYPES = frozenset({"]
    lines += [f'    "{t}",' for t in published] + ["})", "",
                                                    "#: The schema file of each published type.",
                                                    "SCHEMA_FILES = {"]
    lines += [f'    "{t}": "{files[t]}",' for t in published] + ["}", "",
                                                                 "#: Required fields of `data`, per type.",
                                                                 "REQUIRED_DATA_FIELDS = {"]
    lines += [f'    "{t}": ({", ".join(json.dumps(f) for f in required[t])}{"," if len(required[t]) == 1 else ""}),'
              for t in published] + ["}", "",
                                     "#: Closed catalogues: the values the schema allows, per type and field.",
                                     "CATALOGS = {"]
    for t in published:
        if t not in catalogs:
            continue
        lines.append(f'    "{t}": {{')
        for field, values in catalogs[t].items():
            lines.append(f'        "{field}": ({", ".join(json.dumps(v) for v in values)},),')
        lines.append("    },")
    lines += ["}", ""]
    return "\n".join(lines)


def python_enums(found):
    lines = [HEADER_PY, '"""IAES enumerations. Generated from schema/; see the header."""', "",
             "from enum import Enum", ""]
    for name, event_type, field in ENUMS:
        values, description = enum_values(found, event_type, field)
        lines += ["", f"class {name}(str, Enum):",
                  '    """' + wrap(description, 76, "    ").lstrip() + "",
                  "",
                  f"    Schema: {event_type}, data.{field}.",
                  '    """', ""]
        lines += [f'    {v.upper()} = "{v}"' for v in values]
        lines.append("")
    return "\n".join(lines)


def ts_from_schema(published, files, required, catalogs):
    lines = [HEADER_TS, "/** What the schemas say about shape, as data. Generated; see the header. */", "",
             "/** Event types whose schema is published. */",
             "export const PUBLISHED_EVENT_TYPES: ReadonlySet<string> = new Set(["]
    lines += [f'  "{t}",' for t in published] + ["]);", "",
                                                  "/** The schema file of each published type. */",
                                                  "export const SCHEMA_FILES: Readonly<Record<string, string>> = {"]
    lines += [f'  "{t}": "{files[t]}",' for t in published] + ["};", "",
                                                               "/** Required fields of `data`, per type. */",
                                                               "export const REQUIRED_DATA_FIELDS: Readonly<Record<string, readonly string[]>> = {"]
    lines += [f'  "{t}": [{", ".join(json.dumps(f) for f in required[t])}],' for t in published]
    lines += ["};", "",
              "/** Closed catalogues: the values the schema allows, per type and field. */",
              "export const CATALOGS: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = {"]
    for t in published:
        if t not in catalogs:
            continue
        lines.append(f'  "{t}": {{')
        for field, values in catalogs[t].items():
            lines.append(f'    {field}: [{", ".join(json.dumps(v) for v in values)}],')
        lines.append("  },")
    lines += ["};", ""]
    return "\n".join(lines)


def ts_enums(found):
    lines = [HEADER_TS, "/** IAES enumerations. Generated from schema/; see the header. */", ""]
    for name, event_type, field in ENUMS:
        values, description = enum_values(found, event_type, field)
        lines += ["/**", wrap(description, 76, " * "), " *", f" * Schema: {event_type}, data.{field}.", " */",
                  f"export const {name} = {{"]
        lines += [f'  {v.upper()}: "{v}",' for v in values]
        lines += ["} as const;", f"export type {name} = (typeof {name})[keyof typeof {name}];", ""]
    return "\n".join(lines)


def outputs():
    found, published, files, required, catalogs = index()
    return {
        ROOT / "src" / "iaes" / "_from_schema.py": python_from_schema(published, files, required, catalogs),
        ROOT / "src" / "iaes" / "enums.py": python_enums(found),
        ROOT / "npm" / "src" / "fromSchema.ts": ts_from_schema(published, files, required, catalogs),
        ROOT / "npm" / "src" / "enums.ts": ts_enums(found),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if a generated file is stale")
    args = ap.parse_args()
    stale = []
    for path, text in outputs().items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != text:
                stale.append(str(path.relative_to(ROOT)).replace("\\", "/"))
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        print(f"stale: {stale}. Run python tools/generate_from_schema.py", file=sys.stderr)
        sys.exit(1)
    if not args.check:
        print("wrote", ", ".join(str(p.relative_to(ROOT)).replace("\\", "/") for p in outputs()))


if __name__ == "__main__":
    main()
